### ISSUE TITLE
Улетает окно)

### ISSUE THREAD

**Issue by 0test** [Pathologic/commerce-booking#3]
"Резервирование - Создать"
При клике на "Объект" окно улетает к соседям. Экран 1920х1080
![image](https://github.com/Pathologic/commerce-booking/assets/10080727/36ba89dd-f557-4e5d-9666-f85815c57014)

**Comment by Pathologic** [comment]
https://github.com/evocms-community/evolution/commit/125f115cd2d78cffdfc27006a8282672eac3dba4
